---
title: "Exploring the Titanic"
author: "A Key Beyond"
date: "June 24, 2017"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

```{r}
#Importing setting to flag strings and not have R automatically label char as factors.
df.train <- read.csv("train.csv",
                     stringsAsFactors = FALSE,
                      na.strings=c("NA","") 
                      )

df.test <- read.csv("test.csv",
                    stringsAsFactors = FALSE,
                    na.strings=c("NA","")
                    )

#Creating a place holder column in our df
df.test$Survived = 0 

#combine df
df.full  <- rbind(df.train, df.test) 

#Summary
str(df.full)

#Missing data
sapply(df.full, function(df){
    sum(is.na(df==TRUE) /length(df));
    })

#Visualize training data
hist(df.train$Age, 
     main = "Age",
     xlab = "Age",
     col="#1B9E77"
     )

barplot(table(df.train$Survived),
        main="Survived",
        names.arg = c("No",
                      "Yes"
                      ),
        col="#1B9E77"
        )

barplot(table(df.train$Sex),
        main = "Sex",
        names.arg = c("Male",
                      "Female"
                      ),
        col=c("#1B9E77",
              "#D95F02"
              )
        )
barplot(table(df.train$Embarked),
        main = "Embarked",
        names.arg =c( "Cherbourg",
                      "Queenstown",
                      "Southampton"
                    ),
        col=c("#1B9E77",
              "#D95F02",
              "#7570B3"
              )
        )
barplot(table(df.train$Pclass),
        main = "Passenger Class",
        col= c("#1B9E77",
               "#D95F02",
               "#7570B3"
               )
        )

barplot(table(df.train$Parch),
        main = "Parchren and Parents Aboard",
        col=c("#1B9E77",
              "#D95F02",
              "#7570B3",
              "#E7298A",
              "#66A61E",
              "#E6AB02"
              )
        )
        
barplot(table(df.train$SibSp),
        main = "Siblings and Spouse Aboard",
        col=c("#1B9E77",
              "#D95F02",
              "#7570B3",
              "#E7298A",
              "#66A61E",
              "#E6AB02",
              "#A6761D",
              "#666666"
              )
        )

#Post Processing

#Embarked
df.full$Embarked <- as.factor(df.full$Embarked)
summary(df.full$Embarked)
df.full$Embarked[which(is.na(df.full$Embarked))] = 'S'

#Age
summary(df.full$Age)

df.full$Title <- gsub('(.*, )|(\\..*)', '', df.full$Name)

table(df.full$Sex, df.full$Title)
mean.age <- mean(df.full$Age[df.full$Title])

aggregate(df.full$Age,list(df.full$Title),mean)

df.full$Title[df.full$Title == 'Mlle'] <- 'Miss' 
df.full$Title[df.full$Title == 'Ms'] <- 'Miss'
df.full$Title[df.full$Title == 'Mme'] <- 'Mrs' 
df.full$Title[df.full$Title == 'Dona'] <- 'Mrs' 
df.full$Title[df.full$Title == 'the Countess'] <- 'Mrs'
df.full$Title[df.full$Title == 'Lady'] <- 'Mrs'
df.full$Title[df.full$Title == 'Dr' & df.full$Sex == 'female'] <- 'Mrs'
df.full$Title[df.full$Title == 'Jonkheer'] <- 'Mr' 
df.full$Title[df.full$Title == 'Don'] <- 'Mr' 
df.full$Title[df.full$Title == 'Col'] <- 'Mr' 
df.full$Title[df.full$Title == 'Capt'] <- 'Mr' 
df.full$Title[df.full$Title == 'Major'] <- 'Mr' 
df.full$Title[df.full$Title == 'Rev'] <- 'Mr' 
df.full$Title[df.full$Title == 'Sir'] <- 'Mr' 
df.full$Title[df.full$Title == 'Dr' & df.full$Sex == 'male'] <- 'Mr' 

table(df.full$Sex, df.full$Title)

mean.miss = mean(
                df.full$Age[
                            df.full$Title == 'Miss' & !is.na(df.full$Age)
                            ]
                )

mean.mrs = mean(
                df.full$Age[
                            df.full$Title == 'Mrs' & !is.na(df.full$Age)
                            ]
                )


mean.master = mean(
                df.full$Age[
                            df.full$Title == 'Master' & !is.na(df.full$Age)
                            ]
                )


mean.mr = mean(
                df.full$Age[
                            df.full$Title == 'Mr' & !is.na(df.full$Age)
                            ]
                )

df.full$Age[df.full$Title =='Miss' & is.na(df.full$Age)] <- mean.miss
df.full$Age[df.full$Title =='Mrs' & is.na(df.full$Age)] <- mean.mrs
df.full$Age[df.full$Title =='Master' & is.na(df.full$Age)] <- mean.master
df.full$Age[df.full$Title =='Mr' & is.na(df.full$Age)] <- mean.mr



Fare
summary(df.full$Fare)


df.full$FareCat [df.full$Fare < 10 | df.full$Fare == 10] <- 3
df.full$FareCat [df.full$Fare > 10 & df.full$Fare < 20]  <- 2
df.full$FareCat [df.full$Fare > 30]                      <- 1

table(df.full$FareCat, df.full$Pclass)

#using this we can roughly estimate our missing fare value.


est.Fare <- mean(df.full$Fare[df.full$Pclass == df.full$Pclass[is.na(df.full$Fare)] & !is.na(df.full$Fare)])
df.full$Fare[is.na(df.full$Fare)] <- est.Fare

df.full$FareCat [df.full$Fare < 10 | df.full$Fare == 10] <- 3
df.full$FareCat [df.full$Fare > 10 & df.full$Fare < 20]  <- 2
df.full$FareCat [df.full$Fare >= 20]                      <- 1

sapply(df.full, function(df){
    sum(is.na(df==TRUE) /length(df));
    })

# So now we have replaced our NA values in Age with our predictions based upon titles. Missing Embarked values were replaced using the mode, which was South Hampton the starting point of the maiden voyage. Fare was estimated using Pclass, and Cabin was left unchanged as there is too much missing data.


df.train <- df.full[1:891,]
df.test <- df.full[892:1309,]

summary(aov(Survived ~ Pclass + Parch + Age + Sex, df.train))


glm.survived <-  glm(Survived ~ Pclass + Parch + Age + Sex, family = binomial, data = df.train)
pred.survived <- predict(
                          object = glm.survived,
                          newdata = df.test,
                          type = "response"
                          )
df.test$Survived <- as.numeric(as.numeric(pred.survived)>0.5)
write.csv(df.test[,c("PassengerId", "Survived")],"submit.csv", row.names=F)

```
